#!/bin/bash

set -e

git_hash() {
    git log -1 --pretty="%h"
}

todo_count() {
    grep -ri "TODO" . --include="*.go" | wc -l
}

loc_prod() {
    find . -maxdepth 1 -name '*.go' -and -not -name '*_test.go' | xargs cat | wc -l
}

loc_test() {
    find . -maxdepth 1 -name '*_test.go' | xargs cat | wc -l
}

pass_fail() {
    echo "$1" | grep -P "PASS|FAIL"
}

coverage() {
    echo "$1" | grep "coverage" | cut -d ' ' -f 2
}

real_time() {
    echo "$1" | grep real | cut -d ' ' -f 2
}

go_time() {
    echo "$1" | grep "oriolf/bella-ciao" | sed "s/[[:space:]]/ /g" | tr -s ' ' | cut -d ' ' -f 3
}

(
    cd ../backend
    rm -f db.db cover.out
    rm -rf uploads
    if [[ "$1" == "silent" ]]; then
        output="$( (time -p go test -coverprofile cover.out) 2>&1 )"
    else
        output="$( (time -p go test -coverprofile cover.out) 2>&1 | tee /dev/tty)"
    fi
    lp=$(loc_prod)
    lt=$(loc_test)
    echo "$(git_hash),$(pass_fail "$output"),$lp,$lt,$(echo "$lt / $lp" | bc -l),$(todo_count),$(coverage "$output"),$(go_time "$output"),$(real_time "$output")"
)
