#!/bin/bash

set -e

pass_fail() {
    echo "$1" | grep -P "PASS|FAIL"
}

coverage() {
    echo "$1" | grep "coverage"
}

(
    trap "kill 0" EXIT
    cd ../backend
    rm -f db.db
    rm -rf uploads
    go install
    bella-ciao &
    go test -coverprofile cover.out
#    go tool cover -html=cover.out
#    rm cover.out
#    oriol="$(go test -coverprofile cover.out)"
#    echo "$oriol"
#    echo "$(git rev-parse --short HEAD),$(pass_fail "$oriol"),$(coverage "$oriol")" >> stats.csv
#   We want the following data for statistics:
#   commit hash, total number of production code lines, total number of test code lines, ratio test lines/production lines, total number of TODOs, total test time, test time as said by
#   go test, coverage, time to start the backend
#   For the last one, use https://github.com/garybernhardt/destroy-all-software-extras/blob/master/das-0070-time-to-first-request/time_to_first_request.sh
)
